from __future__ import annotations

from dataclasses import dataclass
from typing import Callable


@dataclass(frozen=True)
class PromptContext:
    """Structured prompt-building context passed to prompt wrapper functions.

    Attributes:
        section_name: Codebook section name for the current annotation.
        section_instruction: Optional section-level instructions from the codebook.
        annotation_name: Human-readable annotation label inside the section.
        tooltip: Optional annotation guidance or tooltip text.
        annotation_type: One of ``"dropdown"``, ``"checkbox"``, ``"likert"``, ``"textbox"``, or ``"span"``.
        options: Dropdown options when ``annotation_type`` is ``"dropdown"``, otherwise ``None``.
        min_value: Minimum Likert value when applicable, otherwise ``None``.
        max_value: Maximum Likert value when applicable, otherwise ``None``.
        label_options: Allowed labels when ``annotation_type`` is ``"span"`` and the
            annotation is labelled; ``None`` for plain highlights or non-span types.
        example: Example block extracted from the codebook, if present.
        text: Raw source text being annotated.
        use_examples: Whether examples should be included in the rendered prompt.
        response_instructions: Type-specific response instructions generated by CodeBook Lab.
        core_prompt: Prompt body assembled before the outer wrapper is applied.
    """

    section_name: str
    section_instruction: str
    annotation_name: str
    tooltip: str
    annotation_type: str
    options: list[str] | None
    min_value: int | None
    max_value: int | None
    label_options: list[str] | None
    example: str
    text: str
    use_examples: bool
    response_instructions: str
    core_prompt: str


PromptWrapper = Callable[[PromptContext], str]
PromptType = str | PromptWrapper


def _standard_wrapper(context: PromptContext) -> str:
    """Render the default prompt wrapper for a ``PromptContext``."""
    return f'{context.core_prompt}\n\n---\n\nText: \n"{context.text}"\n\nResponse: \n'


def _persona_wrapper(context: PromptContext) -> str:
    """Render the built-in persona prompt wrapper for a ``PromptContext``."""
    prefix = (
        "You are an expert political scientist and data annotator with extensive "
        "experience in analyzing political discourse and parliamentary debates.\n\n"
        "Task: Annotate the following text using the criteria below. Your annotation "
        "should be precise, consistent, and based solely on the text content.\n\n"
    )
    suffix = f'\n\n---\n\nText: \n"{context.text}"\n\nResponse: \n'
    return f"{prefix}{context.core_prompt}{suffix}"


def _cot_wrapper(context: PromptContext) -> str:
    """Render the built-in chain-of-thought prompt wrapper for a ``PromptContext``."""
    suffix = "\n\nI'll think through this step by step:\n\n"
    suffix += "1. First, I'll identify key parts of the text relevant to this dimension\n"
    suffix += "2. Next, I'll analyze how these elements relate to the annotation criteria\n"
    suffix += "3. Then, I'll consider my assessment carefully\n"
    suffix += "4. Finally, I'll make my selection based on this analysis\n"
    suffix += f'\n\n---\n\nText: \n"{context.text}"\n\n'
    suffix += "Step-by-step analysis:\n\n[Think through your reasoning here]\n\n"
    suffix += "Response: \n"
    return f"{context.core_prompt}{suffix}"


_PROMPT_WRAPPERS: dict[str, PromptWrapper] = {
    "standard": _standard_wrapper,
    "persona": _persona_wrapper,
    "CoT": _cot_wrapper,
}


def register_prompt_wrapper(name: str, wrapper: PromptWrapper, overwrite: bool = False) -> None:
    """Register a prompt wrapper for use in Python and CLI experiment configs.

    Args:
        name: String key users will pass as ``prompt_type`` such as ``"concise"``.
        wrapper: Callable accepting a `PromptContext` and returning a full prompt string.
        overwrite: Set to ``True`` to replace an existing wrapper with the same name.
    """
    if not name:
        raise ValueError("Prompt wrapper name must be a non-empty string.")
    if not overwrite and name in _PROMPT_WRAPPERS:
        raise ValueError(f"Prompt wrapper '{name}' is already registered.")
    _PROMPT_WRAPPERS[name] = wrapper


def get_prompt_wrapper(name: str) -> PromptWrapper:
    """Return a registered prompt wrapper by name.

    Args:
        name: Prompt wrapper key, for example ``"standard"`` or a custom name.

    Returns:
        The callable prompt wrapper registered under ``name``.
    """
    try:
        return _PROMPT_WRAPPERS[name]
    except KeyError as exc:
        available = ", ".join(sorted(_PROMPT_WRAPPERS))
        raise ValueError(
            f"Unknown prompt wrapper '{name}'. Available wrappers: {available}."
        ) from exc


def list_prompt_wrappers() -> list[str]:
    """Return the sorted names of all registered prompt wrappers."""
    return sorted(_PROMPT_WRAPPERS)


def get_prompt_type_name(prompt_type: PromptType) -> str:
    """Return a stable display name for a prompt type or callable wrapper.

    Args:
        prompt_type: Either a registered wrapper name or a callable wrapper.

    Returns:
        A string name suitable for config files and experiment metadata.
    """
    if isinstance(prompt_type, str):
        return prompt_type
    return getattr(prompt_type, "__name__", "custom_prompt_wrapper")


def render_prompt(prompt_type: PromptType, context: PromptContext) -> str:
    """Render a prompt using a registered wrapper name or a direct callable.

    Args:
        prompt_type: Registered wrapper name or callable accepting ``PromptContext``.
        context: Structured prompt inputs for the current annotation.

    Returns:
        A full prompt string ready to send to the model.
    """
    wrapper = get_prompt_wrapper(prompt_type) if isinstance(prompt_type, str) else prompt_type
    return wrapper(context)
